Universe = vanilla
executable = /bos/usr0/yitongz/indri-5.4/buildindex/IndriBuildIndex
arguments = -corpus.path=../../data/_indri_xml_topic/MB004\  -corpus.class=trectext -field.name=CLEANTWEET -index=../../data/_indri_inv/MB004 -indexType=indri
output = /bos/usr0/yitongz/condor/indexbuild/MB004.job.out
log = /bos/usr0/yitongz/condor/indexbuild/MB004.job.log
error = /bos/usr0/yitongz/condor/indexbuild/MB004.job.err
queue
