Universe = vanilla
executable = /bos/usr0/yitongz/indri-5.4/buildindex/IndriBuildIndex
arguments = -corpus.path=../../data/_indri_xml_topic/MB049\  -corpus.class=trectext -field.name=CLEANTWEET -index=../../data/_indri_inv/MB049 -indexType=indri
output = /bos/usr0/yitongz/condor/indexbuild/MB049.job.out
log = /bos/usr0/yitongz/condor/indexbuild/MB049.job.log
error = /bos/usr0/yitongz/condor/indexbuild/MB049.job.err
queue
